### ISSUE TITLE
[extended-copy] Uri won't work in upcomming CLI release

### ISSUE THREAD

**Issue by Tetrax-10** [Pithaya/spicetify-apps#1]
As spotify has totally changed the URI methods `getBase62Id()` wont be available here after. So fix your ext in adavance This is the [patch](https://github.com/pnthach95/spicetify-extensions/pull/7) I made to overcome this issue with backwards compatibility for spicetify/spicetify-cli@93893021694d441a22f9dbf01dc91ae50ae14458

**Comment by Tetrax-10** [comment]
Your extension wont work for users below 1.2.4

**Comment by Pithaya** [comment]
Since Spotify auto updates, is it still necessary if v1.2.4 is already out ?

**Comment by Tetrax-10** [comment]
Linux users latest version is v1.1.89. Most people turn off auto update so spicetify wont go off. Its just one line to fix.

**Comment by Pithaya** [comment]
Oh I see, thanks. I'll change it.
