### ISSUE TITLE
"Made for you" icon not centered in library X view

### ISSUE THREAD

**Issue by lebakhai** [Pithaya/spicetify-apps#17]
before:
![image](https://github.com/Pithaya/spicetify-apps/assets/97871575/1c39fcc4-0b14-4b02-80f1-508cc1e7a185)

after:
![image](https://github.com/Pithaya/spicetify-apps/assets/97871575/32ca3736-6d6f-4887-a2c3-473a199a25d3)

css:
.main-navBar-navBarItem[data-id="/genre/made-for-x-hub"] {
  padding: 4px 12px !important;  
}

.main-navBar-navBarItem[data-id="/genre/made-for-x-hub"] .link-subtle.main-navBar-navBarLink  {
  padding: 0px !important;;  
}

**Comment by Pithaya** [comment]
Fixed in #20
