### ISSUE TITLE
extension is not working at all

### ISSUE THREAD

**Issue by squoosh4** [Pithaya/spicetify-apps#35]
![image](https://github.com/Pithaya/spicetify-apps/assets/110200988/611872b2-2f3f-4d49-b26a-561fdd859413)
![image](https://github.com/Pithaya/spicetify-apps/assets/110200988/fd25cc23-d5e0-4fca-9a11-a00c1fe5392d)

i click the button and 2 notifications pop up above the bottom toolbar. (first image)
i go to the eternal jukebox tab on the left side and it throws an error. (second image)

is there any fix for this? what is happening?

**Comment by pragit-raj-sharma** [comment]
same

**Comment by squoosh4** [comment]
thank you 🗣️🙏🔥‼️
